---
title: "Exploratory Data Analysis"
author: "Joy Zhang"
date: "2023-12-13"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(gridExtra)
library(ggpubr)
library(table1)

diabetes_data <- read.csv("diabetes_data.csv")
```

# Factor covariates as necessary
```{r}
diabetes_data$Diabetes_binary <- factor(diabetes_data$Diabetes_binary)
diabetes_data$HighBP <- factor(diabetes_data$HighBP)
diabetes_data$HighChol <- factor(diabetes_data$HighChol)
diabetes_data$CholCheck <- factor(diabetes_data$CholCheck)
diabetes_data$Smoker <- factor(diabetes_data$Smoker)
diabetes_data$Stroke <- factor(diabetes_data$Stroke)
diabetes_data$HeartDiseaseorAttack <- factor(diabetes_data$HeartDiseaseorAttack)
diabetes_data$PhysActivity <- factor(diabetes_data$PhysActivity)
diabetes_data$Fruits <- factor(diabetes_data$Fruits)
diabetes_data$Veggies <- factor(diabetes_data$Veggies)
diabetes_data$HvyAlcoholConsump <- factor(diabetes_data$HvyAlcoholConsump)
diabetes_data$AnyHealthcare <- factor(diabetes_data$AnyHealthcare)
diabetes_data$NoDocbcCost <- factor(diabetes_data$NoDocbcCost)
diabetes_data$DiffWalk <- factor(diabetes_data$DiffWalk)
diabetes_data$Sex <- factor(diabetes_data$Sex)
diabetes_data$age_cat <- factor(diabetes_data$age_cat)
diabetes_data$income_cat <- factor(diabetes_data$income_cat)
diabetes_data$edu_cat <- factor(diabetes_data$edu_cat)
diabetes_data$PhysHlth_cat <- factor(diabetes_data$PhysHlth_cat)
diabetes_data$MentHlth_cat <- factor(diabetes_data$MentHlth_cat)
```

# Table One
```{r}
table1(~ Diabetes_binary + HighBP + HighChol + CholCheck + Smoker + Stroke + HeartDiseaseorAttack + PhysActivity + Fruits + Veggies + HvyAlcoholConsump + AnyHealthcare + NoDocbcCost + DiffWalk + Sex + income_cat + edu_cat + PhysHlth_cat + MentHlth_cat | age_cat, data = diabetes_data)
```


# Plots to see distribution of different covariates 
```{r}
# Diabetes by age
ggplot(diabetes_data) + 
  geom_bar(aes(x = Diabetes_binary, fill = factor(age_cat)), position = "fill") + 
  ggtitle("Diabetes Categorized by Age") + 
  labs(x = "Diabetes", y = "Proportion", fill = "Age Category") + 
  scale_fill_discrete(labels = c("Under 35", "36-49", "50-64", "Over 65"))

# Histogram of age
ggplot(diabetes_data) + 
  geom_bar(aes(x = age_cat)) + 
  ggtitle("Distribution of Age") + 
  labs(x = "Age")

# Histogram of High Blood Pressure
BP_plot <- ggplot(diabetes_data) + 
  geom_bar(aes(x = factor(HighBP), fill = factor(age_cat)), position = "fill") +
  #ggtitle("High Blood Pressure") + 
  labs(x = "High Blood Pressure", y = "Proportion", fill = "Age Category") + 
  scale_fill_discrete(labels = c("Under 35", "36-49", "50-64", "Over 65"))

# Histogram of High Chloesterol
chol_plot <- ggplot(diabetes_data) + 
  geom_bar(aes(x = factor(HighChol), fill = factor(age_cat)), position = "fill") +
  #ggtitle("High Cholesterol Categorized by Age") + 
  labs(x = "High Cholesterol", y = "Proportion", fill = "Age Category") + 
  scale_fill_discrete(labels = c("Under 35", "36-49", "50-64", "Over 65"))

# Histogram of Smoking Status
smoker_plot <- ggplot(diabetes_data) + 
  geom_bar(aes(x = factor(Smoker), fill = factor(age_cat)), position = "fill") +
  #ggtitle("Smoking Status by Age") + 
  labs(x = "Smoking Status", y = "Proportion", fill = "Age Category") + 
  scale_fill_discrete(labels = c("Under 35", "36-49", "50-64", "Over 65"))

# Histogram of High Blood Pressure
stroke_plot <- ggplot(diabetes_data) + 
  geom_bar(aes(x = factor(Stroke), fill = factor(age_cat)), position = "fill") +
  #ggtitle("Stroke Categorized by Age") + 
  labs(x = "Stroke", y = "Proportion", fill = "Age Category") + 
  scale_fill_discrete(labels = c("Under 35", "36-49", "50-64", "Over 65"))

# Histogram of Heart Disease
heart_disease_plot <- ggplot(diabetes_data) + 
  geom_bar(aes(x = factor(HeartDiseaseorAttack), fill = factor(age_cat)), position = "fill") +
  #ggtitle("Heart Disease Categorized by Age") + 
  labs(x = "Heart Disease", y = "Proportion", fill = "Age Category") + 
  scale_fill_discrete(labels = c("Under 35", "36-49", "50-64", "Over 65"))

EDA_health <- ggarrange(BP_plot, chol_plot, stroke_plot, heart_disease_plot, common.legend = T, legend = "bottom")

annotate_figure(EDA_health, top = text_grob("Health Indicators Categorized by Age", 
               color = "black", face = "bold", size = 16))
```
