---
title: "Model Building"
author: "Joy Zhang"
date: "2023-12-13"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
diabetes_data <- read.csv("diabetes_data.csv")
```

# Factor covariates as necessary
```{r}
diabetes_data$Diabetes_binary <- factor(diabetes_data$Diabetes_binary)
#levels(diabetes_data$Diabetes_binary) <- c("No Diabetes", "Diabetes or Pre-Diabetic")
diabetes_data$HighBP <- factor(diabetes_data$HighBP)
diabetes_data$HighChol <- factor(diabetes_data$HighChol)
diabetes_data$Smoker <- factor(diabetes_data$Smoker)
diabetes_data$Stroke <- factor(diabetes_data$Stroke)
diabetes_data$HeartDiseaseorAttack <- factor(diabetes_data$HeartDiseaseorAttack)
diabetes_data$PhysActivity <- factor(diabetes_data$PhysActivity)
diabetes_data$Fruits <- factor(diabetes_data$Fruits)
diabetes_data$Veggies <- factor(diabetes_data$Veggies)
diabetes_data$HvyAlcoholConsump <- factor(diabetes_data$HvyAlcoholConsump)
diabetes_data$AnyHealthcare <- factor(diabetes_data$AnyHealthcare)
diabetes_data$NoDocbcCost <- factor(diabetes_data$NoDocbcCost)
diabetes_data$GenHlth <- factor(diabetes_data$GenHlth)
diabetes_data$DiffWalk <- factor(diabetes_data$DiffWalk)
diabetes_data$Sex <- factor(diabetes_data$Sex)
```

# Fit first model with just age
```{r}
model1 <- glm(data = diabetes_data, formula = factor(Diabetes_binary) ~ factor(age_cat), family = binomial("logit"))
summary(model1)
```

# Fit model with all covariates
```{r}
model2 <- glm(data = diabetes_data, formula = Diabetes_binary_numeric ~ HighBP + HighChol + CholCheck + Smoker + Stroke + HeartDiseaseorAttack + PhysActivity + Fruits + Veggies + HvyAlcoholConsump, family = binomial("logit"))
summary(model2)
```




